{
 "title": "Faraz eks simulation minikube dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pod Container Restart Increase (1 Minute)",
   "type": "timeseries",
   "description": "This panel shows the number of pod container restarts that have occurred over the past minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Restarts" } },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Podo CPU Usage (Cores)",
   "type": "timeseries",
   "description": "Shows CPU cores used per pod over time.\nExcludes system container (container='POD').\nUpdated every 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{container!='POD'}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (MB)",
   "type": "timeseries",
   "description": "Displays working memory set per pod.\nFiltered to exclude system containers.\nReal time updates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container!=\"POD\"}) / 1048576",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}