apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  namespace: minio-storage
spec:
  podSelector: {}  # applies to all pods in this namespace
  policyTypes:
  - Ingress
  ingress: []