apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-logger-script
  namespace: system
data:
  entrypoint.sh: |
    #!/bin/sh
    echo "[INFO] Starting httpbin with Authorization header logging leaks..."
    
    # Create log directory
    mkdir -p /var/log/gunicorn
    
    # Configure Gunicorn to log headers directly
    exec gunicorn \
      --access-logfile - \
      --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "AUTH_HEADER: %({Authorization}i)s"' \
      -b 0.0.0.0:80 \
      httpbin:app