apiVersion: v1
kind: Service
metadata:
  name: faraz-minio
  namespace: minio-storage
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP