apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: faraz-gateway-deploy
    path: gateway/replica-patch.yaml
  - target:
      kind: Deployment
      name: faraz-auth-service-deploy
    path: auth-service/replica-patch.yaml
  - target:
      kind: Deployment
      name: faraz-auth-service-deploy
    path: auth-service/debug-sidecar-patch.yaml
  - target:
      kind: Deployment
      name: faraz-data-service-deploy
    path: data-service/replica-patch.yaml
  - target:
      kind: Deployment
      name: faraz-data-service-deploy
    path: data-service/debug-sidecar-patch.yaml
  # - target:
  #     kind: Deployment
  #     name: faraz-data-service-deploy
  #   path: data-service/service-account-patch.yaml