apiVersion: v1
kind: Service
metadata:
  name: faraz-auth-service-svc
  namespace: system
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP