apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-auth-service-deploy
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: auth-service
        command: ["/bin/sh", "/entrypoint.sh"]
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--log-level debug"
        volumeMounts:
        - name: auth-logger-script
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
          readOnly: true
      volumes:
      - name: auth-logger-script
        configMap:
          name: auth-logger-script
          defaultMode: 0555