apiVersion: apps/v1
kind: Deployment
metadata:
  name: faraz-auth-service-deploy
spec:
  template:
    spec:
      serviceAccountName: faraz-auth-service-sa
      containers:
        - name: auth-service
          envFrom:
            - secretRef:
                name: faraz-minio-credentials