apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/system-namespace.yaml
  - namespaces/application-namespace.yaml
  - microservices/gateway
  - microservices/auth-service
  - microservices/data-service
  - secrets/minio-credentials.yaml
  - service-accounts/data-service-service-account.yaml
  - service-accounts/auth-service-service-account.yaml
  - rbac/minio-secret-reader-role.yaml
  - rbac/minio-secret-reader-role-binding.yaml
  # - clusterpolicies/restrict-secret-mount-to-data-service.yaml