apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/system-namespace.yaml
  - namespaces/application-namespace.yaml
  - microservices/gateway
  - microservices/auth-service
  - microservices/data-service