apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: faraz-gateway-deploy
    path: gateway/replica-patch.yaml
  - target:
      kind: Deployment
      name: faraz-auth-service-deploy
    path: auth-service/replica-patch.yaml
  - target:
      kind: Deployment
      name: faraz-data-service-deploy
    path: data-service/replica-patch.yaml
  - target:
      kind: Service
      name: faraz-auth-service-svc
    path: auth-service/service-type-patch.yaml
  - target:
      kind: Service
      name: faraz-data-service-svc
    path: data-service/service-type-patch.yaml