apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: faraz-minio-secret-reader
  namespace: system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["faraz-minio-credentials"]
    verbs: ["get", "list"]