apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faraz-bind-minio-secret-reader
  namespace: system
subjects:
  - kind: ServiceAccount
    name: faraz-data-service-sa
    namespace: system
roleRef:
  kind: Role
  name: faraz-minio-secret-reader
  apiGroup: rbac.authorization.k8s.io